//! Repository automation. Kept in Rust rather than shell so the release path
//! has the same type checking and the same tests as the product.
//!
//! `test-quick` is what the pre-push hook runs, so it stays fast by
//! construction: it never invokes the integration or E2E adapters. Those are
//! slow enough to train a maintainer into bypassing the hook, and they belong
//! to the scheduled workflow instead.
#![forbid(unsafe_code)]

use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

/// The two modules a unit test may not reach, as one regex.
///
/// `src/main.rs` is the process boundary -- arguments, standard input, the
/// working directory, the two output streams. `src/runtime/disk.rs` is the only
/// module that talks to `std::fs`. Both are proved by the integration and E2E
/// adapters running the whole corpus through them, which is a stronger claim
/// than a line count and the reason neither is in the denominator here.
const EXCLUDED_FROM_COVERAGE: &str = r"src/(main\.rs|runtime/disk\.rs)";

/// The one generated configuration schema that ships beside every release
/// archive. Its contents derive from the typed product model and are checked in
/// before the release writer stages them.
const SCHEMA_ASSET: &str = "rhino-repo-config-v2.schema.json";
const SCHEMA_SOURCE: &str = "schemas/repo-config/v2.schema.json";

fn main() -> ExitCode {
    let task = std::env::args().nth(1);
    let result = match task.as_deref() {
        Some("test-quick") => test_quick(),
        Some("self-validate") => self_validate(),
        Some("schema") => schema(),
        Some("dist") => dist(),
        Some("checksums") => checksums(),
        other => {
            eprintln!("unknown task: {other:?}");
            eprintln!("tasks: test-quick, self-validate, schema, dist, checksums");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("{message}");
            ExitCode::FAILURE
        }
    }
}

/// Write the checked-in Draft 2020-12 schema, or prove it has not drifted.
///
/// The bytes come from RHINO's parser model; this command owns only the file
/// boundary. That keeps a checked-in artifact useful to editors without making
/// a hand-maintained JSON document a second configuration contract.
fn schema() -> Result<(), String> {
    let root = repository_root();
    let path = root.join(SCHEMA_SOURCE);

    if std::env::args()
        .skip(2)
        .any(|argument| argument == "--check")
    {
        return check_schema(&path);
    }

    let parent = path
        .parent()
        .ok_or_else(|| format!("{} has no parent directory", path.display()))?;
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("creating {}: {error}", parent.display()))?;
    std::fs::write(&path, grouped_schema_bytes()?)
        .map_err(|error| format!("writing {}: {error}", path.display()))
}

fn grouped_schema_bytes() -> Result<Vec<u8>, String> {
    rhino::config::v0_4_schema_bytes()
        .map_err(|error| format!("serializing grouped schema: {error}"))
}

fn check_schema(path: &Path) -> Result<(), String> {
    let actual =
        std::fs::read(path).map_err(|error| format!("reading {}: {error}", path.display()))?;
    if actual == grouped_schema_bytes()? {
        Ok(())
    } else {
        Err(format!(
            "{} differs from the schema generated by the configuration model; run `cargo xtask schema`",
            path.display()
        ))
    }
}

fn run(program: &str, args: &[&str]) -> Result<(), String> {
    let status = Command::new(program)
        .args(args)
        .status()
        .map_err(|error| format!("failed to start {program}: {error}"))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!("{program} {} failed", args.join(" ")))
    }
}

fn test_quick() -> Result<(), String> {
    run("cargo", &["fmt", "--all", "--check"])?;
    run(
        "cargo",
        &[
            "clippy",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
        ],
    )?;
    // The fast library suite and the unit adapter run in one coverage
    // measurement. The adapter drives the whole corpus in process against an
    // in-memory tree; integration and E2E touch a real filesystem and a spawned
    // process, and the gate contract puts both in the scheduled workflow rather
    // than in a hook.
    //
    // Measured in the same execution rather than in a second one, because two
    // runs can disagree and the number that gates has to be the number the
    // passing run produced. `main.rs` and the concrete filesystem tree are the
    // only exclusions; `README.md` says what they are and why a unit test may
    // not reach them.
    run(
        "cargo",
        &[
            "llvm-cov",
            "--lib",
            "--test",
            "unit",
            "--fail-under-lines",
            "99",
            "--ignore-filename-regex",
            EXCLUDED_FROM_COVERAGE,
            "--summary-only",
        ],
    )?;
    // The static behaviour check executes no scenario: it asserts that every
    // scenario in the corpus is bound at every layer, or validly exempt. It is
    // in the quick gate because an unbound scenario reports nothing, and
    // reporting nothing looks exactly like passing.
    run("cargo", &["test", "--test", "coverage"])?;
    // The editor artifact is generated from the typed model. This belongs in
    // the quick gate so the pre-push hook and its PR mirror reject byte drift
    // before the native release matrix discovers it.
    check_schema(&repository_root().join(SCHEMA_SOURCE))?;
    // The validators used to run here, last, so that a repository which is out of
    // date could not mask a product that is broken. They still run last -- the
    // `pre-push` surface declares this gate ahead of them in `repo-config.yml`,
    // and the same ordering is written down there with the same reason. What
    // changed is who owns the list.
    Ok(())
}

/// Run this repository's own immutable pull-request gate surface.
///
/// A second corpus that no one wrote: the tree changes constantly, nobody
/// curates it as test data, and every page in it is something a maintainer
/// actually wanted to say. That is the property the executable corpus cannot
/// have, and the reason this runs on every push rather than once.
///
/// The list of commands used to live here, as a nine-entry array. It now lives
/// in `repo-config.yml` under `gates`, where every consumer of this tool
/// declares the same thing -- and where a reader can see the order and the
/// surfaces without reading Rust. This task is the entry point, not the
/// registry; it hands the question to the surface and reports the answer.
///
/// A finding fails the gate exactly as a failing test does: exit 1 means
/// RHINO's own tree violates RHINO's own `repo-config.yml`, and exit 2 means the
/// configuration or the invocation is unusable. Neither is a warning.
fn self_validate() -> Result<(), String> {
    // Built once up front so a compile error is reported as a compile error
    // rather than as the first gate failing to start.
    run("cargo", &["build", "--quiet"])?;
    let root = repository_root();
    let base = match std::env::var("RHINO_GATE_BASE") {
        Ok(value) => value,
        Err(_) => git_revision(&root, "HEAD^")?,
    };
    let head = match std::env::var("RHINO_GATE_HEAD") {
        Ok(value) => value,
        Err(_) => git_revision(&root, "HEAD")?,
    };
    run(
        "./target/debug/rhino",
        &[
            "gate",
            "run",
            "--surface",
            "pull-request",
            "--base",
            &base,
            "--head",
            &head,
        ],
    )
}

fn git_revision(root: &Path, revision: &str) -> Result<String, String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["rev-parse", "--verify", "--end-of-options", revision])
        .output()
        .map_err(|error| format!("resolving {revision}: {error}"))?;
    if !output.status.success() {
        return Err(format!("resolving {revision} failed"));
    }
    String::from_utf8(output.stdout)
        .map_err(|_| format!("Git returned non-UTF-8 output for {revision}"))
        .map(|value| value.trim().to_string())
}

// -- Release artifacts --------------------------------------------------------

/// Build this platform's release archive into `dist/`.
///
/// One platform per invocation, deliberately. The release matrix builds each
/// archive on a runner of that architecture rather than cross-compiling, so
/// every published executable has actually started on the operating system it
/// claims to run on -- the one property a cross-compiled artifact cannot
/// demonstrate about itself. This task is what each of those runners calls, and
/// what a maintainer calls locally to get the same archive for the machine in
/// front of them.
///
/// It assembles rather than verifies. `cargo test --package xtask` reads what
/// this leaves behind, so the checks live outside the thing they check.
fn dist() -> Result<(), String> {
    let root = repository_root();
    let target = host_target()?;
    let output = root.join("dist");

    run("cargo", &["build", "--release"])?;

    std::fs::create_dir_all(&output).map_err(|error| format!("creating dist: {error}"))?;

    let built = root.join("target/release/rhino");
    if !built.exists() {
        return Err(format!("{} was not built", built.display()));
    }

    // Staged under its plain name as well as archived, so the verification
    // tests can run the exact bytes that go into the archive rather than a
    // second build of the same source.
    let staged = output.join("rhino");
    std::fs::copy(&built, &staged).map_err(|error| format!("staging the executable: {error}"))?;

    let archive = format!("rhino-{target}.tar.gz");
    run_in(
        &output,
        "tar",
        &["--create", "--gzip", "--file", &archive, "rhino"],
    )?;

    stage_schema(&root, &output)?;
    write_checksums(&output)?;

    let size = std::fs::metadata(&staged)
        .map_err(|error| format!("measuring the executable: {error}"))?
        .len();
    println!("dist/{archive}");
    println!("stripped executable: {size} bytes");
    Ok(())
}

/// Rewrite `dist/checksums.txt` from whatever archives are there now.
///
/// `dist` already does this for the one archive it built. The release matrix
/// assembles the other three from separate runners, so the job that collects
/// them needs the same writer rather than a second one spelled in shell: one
/// digest file, written by one implementation, however many legs produced it.
fn checksums() -> Result<(), String> {
    let root = repository_root();
    let output = root.join("dist");
    stage_schema(&root, &output)?;
    write_checksums(&output)?;
    print!(
        "{}",
        std::fs::read_to_string(output.join("checksums.txt"))
            .map_err(|error| format!("reading checksums: {error}"))?
    );
    Ok(())
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the xtask crate sits inside the repository")
        .to_path_buf()
}

/// The triple this machine builds for, asked of the compiler rather than
/// guessed from the operating system: a name that did not come from `rustc` is
/// a name that can disagree with what was actually produced.
fn host_target() -> Result<String, String> {
    let output = Command::new("rustc")
        .arg("-vV")
        .output()
        .map_err(|error| format!("failed to start rustc: {error}"))?;
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .find_map(|line| line.strip_prefix("host: "))
        .map(str::to_string)
        .ok_or_else(|| "rustc did not report a host triple".to_string())
}

/// Stage the checked-in schema only when it still matches the typed model.
///
/// A release must not repair schema drift by generating a different artifact at
/// publish time. The checked-in source is what review approved; comparison here
/// makes drift a release failure, then writes those exact bytes beside archives.
fn stage_schema(root: &Path, output: &Path) -> Result<(), String> {
    let source = root.join(SCHEMA_SOURCE);
    let actual =
        std::fs::read(&source).map_err(|error| format!("reading {}: {error}", source.display()))?;
    let expected = rhino::config::v0_4_schema_bytes()
        .map_err(|error| format!("serializing grouped schema: {error}"))?;
    if actual != expected {
        return Err(format!(
            "{} differs from the grouped configuration model; run `cargo xtask schema` before release",
            source.display()
        ));
    }
    std::fs::write(output.join(SCHEMA_ASSET), actual)
        .map_err(|error| format!("staging {SCHEMA_ASSET}: {error}"))
}

/// Record a digest for every release asset in `dist/`, replacing any earlier file.
///
/// Rewritten wholesale rather than appended to, so a second run cannot leave
/// two lines for one archive and let a reader take the stale one.
fn write_checksums(output: &Path) -> Result<(), String> {
    let mut assets: Vec<String> = std::fs::read_dir(output)
        .map_err(|error| format!("reading dist: {error}"))?
        .flatten()
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .filter(|name| is_release_asset(name))
        .collect();
    assets.sort();

    let mut lines = String::new();
    for name in assets {
        let bytes = std::fs::read(output.join(&name))
            .map_err(|error| format!("reading {name}: {error}"))?;
        let mut digest = Sha256::new();
        digest.update(&bytes);
        // Two spaces between digest and name: the format `shasum -c` and
        // `sha256sum -c` both read, so a consumer verifies with the tool their
        // platform already has rather than one this release picked for them.
        let rendered: String = digest
            .finalize()
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect();
        lines.push_str(&format!("{rendered}  {name}\n"));
    }
    std::fs::write(output.join("checksums.txt"), lines)
        .map_err(|error| format!("writing checksums: {error}"))
}

fn is_release_asset(name: &str) -> bool {
    name.ends_with(".tar.gz") || name == SCHEMA_ASSET
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn release_assets_include_each_archive_and_the_grouped_schema() {
        assert!(is_release_asset("rhino-aarch64-apple-darwin.tar.gz"));
        assert!(is_release_asset("rhino-x86_64-apple-darwin.tar.gz"));
        assert!(is_release_asset("rhino-x86_64-unknown-linux-gnu.tar.gz"));
        assert!(is_release_asset("rhino-aarch64-unknown-linux-gnu.tar.gz"));
        assert!(is_release_asset(SCHEMA_ASSET));
        assert!(!is_release_asset("checksums.txt"));
    }
}

fn run_in(directory: &Path, program: &str, args: &[&str]) -> Result<(), String> {
    let status = Command::new(program)
        .args(args)
        .current_dir(directory)
        .status()
        .map_err(|error| format!("failed to start {program}: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{program} {} failed", args.join(" ")))
    }
}
